### ISSUE TITLE
Available in Maven?

### ISSUE THREAD

**Issue by robross0606** [RobertBColton/DockFX#32] opened 2017-03-29 23:03 UTC
You use Maven POM, but I do not see Maven deployed in any available repos.  Is this project accessible as a dependency from Maven?

**Comment by RobertBColton** [comment] 2018-02-13 00:07
Right, I wasn't familiar with what Maven actually was at the time. I will look into but I have to close this because it is a duplicate of #23.

**Closed by RobertBColton** 2018-02-13 00:07 UTC
