### ISSUE TITLE
Dragged pane is behind window

### ISSUE THREAD

**Issue by robross0606** [RobertBColton/DockFX#29] opened 2017-02-04 15:28 UTC
On all demos and testing, any window being dragged is oddly behind the main window.  A nice method would be to a snapshot image of the pane upon dragging, resize to thumbnail, make semi-transparent, and tie it to the mouse movement so you know what it is you are dragging around.

**Comment by RobertBColton** [comment] 2018-02-13 00:21
I am not able to reproduce this and am having trouble deciphering what you meant. Can you please give me some more information about this issue? What Java version and vendor were you testing with and what operating system were you testing on? I just tested with `jre1.8.0_101` on Windows 10 and the dragging is over and on top of the main window, as it shows in the screenshots in my README.md. Please include a screenshot if you can.

**Comment by RobertBColton** [comment] 2018-02-25 23:18
I believe that you were referring to how the DockNodes are always behind the dock indicator overlay. This was entirely deliberate and intentional on my part as it is the way that Visual Studio's docking has always worked, and continues to work in the 2017 release:

![Visual Studio Docking Underneath Overlay](https://user-images.githubusercontent.com/3212801/36647728-f5c0d950-1a57-11e8-8674-97c93ddfe24d.png)

So I am going to close this because otherwise, if you change it, you wouldn't be able to see where the indicators even are. Also, it's been about 2 weeks and I haven't received any other clarification of what you meant. So if you would still like to discuss changing it, or perhaps I misunderstood you, please post back and I will hear you out and or reopen this issue.

Closing as resolved, for now.

**Closed by RobertBColton** 2018-02-25 23:18 UTC

**Comment by robross0606** [comment] 2018-02-27 21:35
No, that’s not what I was talking about. The dragged window would be behind the window from which it was being dragged.

**Comment by RobertBColton** [comment] 2018-02-28 00:55
@robross0606 Thanks, can you show me a screenshot and steps to reproduce it? I can't seem to reproduce it.

**Comment by robross0606** [comment] 2018-02-28 01:06
It has been a long while since I even tried this. I’ll revisit as soon as I can.

**Comment by RobertBColton** [comment] 2018-02-28 01:22
Thanks, yeah. What I think you are describing is that dragging the window out is somehow going behind the entire window, which I can't reproduce. It could have been a JavaFX regression that has since been resolved, perhaps with OpenJDK. Let me know whenever you have time.

**Comment by robross0606** [comment] 2018-02-28 01:40
Strictly Oracle Java 8, though I don’t recall the exact build. I’ll try again some time next week when I’m able.
