### ISSUE TITLE
Way to keep windows state

### ISSUE THREAD

**Issue by PawelSzymanski89** [RobertBColton/DockFX#39] opened 2019-04-01 06:49 UTC
How to restore panes after program reload?

**Comment by RobertBColton** [comment] 2020-10-30 02:52
Serialization of the layout isn't supported yet. Also this is a duplicate of #11 so I will need to close it, please monitor that issue for further updates regarding the feature if it does end up getting added.

**Closed** 2020-10-30 02:54 UTC
Labels: Enhancement
