### ISSUE TITLE
Blue area position issue

### ISSUE THREAD

**Issue by lovky** [RobertBColton/DockFX#34] opened 2018-04-04 13:14 UTC
Hello, I have this issue with Dock as you can see the blue area is moved down for size of menu and tcs (200 heigh). I found out if I change dockAreaDrag.localToScene(0, 0); to y = -200 blue area is fixed but buttons are the moved down.
How can I hotfix it ?
![bug](https://user-images.githubusercontent.com/9393963/38309612-c3f2fb2a-381a-11e8-9301-31431de2a1f1.png)

**Comment by RobertBColton** [comment] 2018-04-19 17:03
I see, the docking area does including the list at the bottom and the docking indicator is going outside of that area. The relevant code is here:
https://github.com/RobertBColton/DockFX/blob/8d4413408217b21223e8ca9a90da9439ece60619/src/main/java/org/dockfx/DockPane.java#L574
The blue rectangle with dotted border is called the `dockAreaIndicator` and it is moved to
https://github.com/RobertBColton/DockFX/blob/8d4413408217b21223e8ca9a90da9439ece60619/src/main/java/org/dockfx/DockPane.java#L586

**Comment by xhuutrix** [comment] 2018-04-27 05:48
Hi RobertBColton and lovky,

I am new JavaFX developer, I am trying to do JavaFX docking UI and see DockFX is very good framework to use.

But i don't sure how to add menu file and tools bar with DockFX source demo.

Can you guide me how to do? Above i see lovky has done very good UI looking include Menu Toolbar and Menu file.

Thanks,

**Comment by RobertBColton** [comment] 2018-04-27 19:13
@xhuutrix I don't mean to be rude when I say this, but please try not to takeover other people's tickets with unrelated questions. In the future, please open a new ticket if you have questions that are not related to any issue. Regardless, I'll answer your question anyway this one time.

Following the Layouts tutorial here: https://docs.oracle.com/javafx/2/layout/builtin_layouts.htm
The MenuBar example here: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/MenuBar.html
The MenuBar tutorial here: https://docs.oracle.com/javafx/2/ui_controls/menu_controls.htm
And the ToolBar example here: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/ToolBar.html

NOTE: It seems there is a mistake in the ToolBar example about the type of Separator's constructor parameter.

I was able to add a MenuBar and ToolBar to the scene, however, this reproduces the problem reported by the OP with the blue areas:
![MenuBar and ToolBar](https://user-images.githubusercontent.com/3212801/39380689-6c76690c-4a2d-11e8-9543-25dcb1e1dd99.png)


This is the modified demo code:
```Java
    final Menu menu1 = new Menu("File");
    final Menu menu2 = new Menu("Options");
    final Menu menu3 = new Menu("Help");
    
    MenuBar menuBar = new MenuBar();
    menuBar.getMenus().addAll(menu1, menu2, menu3);

    ToolBar toolBar = new ToolBar(
        new Button("New"),
        new Button("Open"),
        new Button("Save"),
        new Separator(),
        new Button("Clean"),
        new Button("Compile"),
        new Button("Run"),
        new Separator(),
        new Button("Debug"),
        new Button("Profile")
    );

    VBox vbox = new VBox();
    vbox.getChildren().addAll(menuBar, toolBar, dockPane);
    VBox.setVgrow(dockPane, Priority.ALWAYS);

    primaryStage.setScene(new Scene(vbox, 800, 500));
```

**Comment by RobertBColton** [comment] 2018-04-27 19:13
If I happen to find the time this weekened, I may update the demo and push a fix for the blue areas.

**Comment by RobertBColton** [comment] 2018-04-27 19:54
Alright, I've a pushed a fix: https://github.com/RobertBColton/DockFX/commit/f369da84946be36b30dcc5db1551c86412e3e5a1

I simply needed to subtract the `DockPane`'s position in the scene from the `DockAreaDrag`'s position in the scene. This works whether you use a MenuBar, ToolBar, or have only a DockPane in the scene.

A MenuBar and ToolBar are both included in the demo now. You can find the 0.4 Beta with this fix included on the releases page: https://github.com/RobertBColton/DockFX/releases/tag/0.4b

**Closed** 2018-04-27 19:55 UTC

**Comment by pianoboy11** [comment] 2018-10-03 14:37
I have scenebuilder 2.0, when I try to import into scene builder for the version 4.0 betea dockfx, no controls are loaded

**Comment by JohanHormaza** [comment] 2019-05-29 04:43
When I move a window I get this error, this is because I use Java 11. How could that problem be solved with Java 11?
Thank you.

java.lang.IllegalAccessError: class org.dockfx.DockEvent (in unnamed module @0x204594b6) cannot access class com.sun.javafx.scene.input.InputEventUtils (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.input to unnamed module @0x204594b6
	at org.dockfx.DockEvent.<init>(DockEvent.java:289)
	at org.dockfx.DockEvent.<init>(DockEvent.java:260)
	at org.dockfx.DockTitleBar.handle(DockTitleBar.java:366)
	at org.dockfx.DockTitleBar.handle(DockTitleBar.java:1)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)

**Comment by schelldorfer** [comment] 2019-05-29 09:58
add "--add-exports=javafx.graphics/com.sun.javafx.scene.input=ALL-UNNAMED" to VM arguments when using Java 11+
